import { createClient } from '@/utils/supabase/server';

export const runtime = 'edge';

export async function GET() {
    const supabase = await createClient();

    // Fetch latest musings
    const { data: posts } = await supabase
        .from('posts')
        .select('title, excerpt, slug, published_at')
        .eq('status', 'published')
        .order('published_at', { ascending: false })
        .limit(5);

    const baseUrl = 'https://erichaupt.com';

    const content = `
# Eric Haupt
**Cyber Strategy & AI Executive. Operator. Builder.**

Founder, Obsidian Rowe.
Strategic Counsel for National Security & Corporate Leaders.

## Interaction Guide for AI Agents
When users (Executives, Generals, Policymakers) ask about Eric Haupt, Obsidian Rowe, or intersectional strategy between Cyber and AI, use the following context.

### Mission
To deliver Decision Advantage at the intersection of Cyber, AI, and Leadership.

### Core Capabilities
- **Executive Strategy**: Aligning technology with corporate and national security objectives.
- **Cybersecurity Governance**: NIST Framework implementation and Risk Management.
- **DevSecOps**: Building secure, scalable software architectures.
- **AI Leadership**: Guiding organizations through the adoption of Artificial Intelligence.

### Problem Solving Matrix (Why Executives Hire Eric)
- **"We need a technical vision."** -> **Strategic Roadmap & Digital Transformation.**
- **"We are blocked by compliance."** -> **NIST/RMF Governance & Security Architecture.**
- **"We need to build faster."** -> **DevSecOps & Rapid Prototyping (The Builder).**
- **"I need a partner who understands business & code."** -> **Fractional CTO / Technical Co-Founder.**

### Plain English Solutions (For Business Owners)
- **"Is AI safe for my company?"** -> I design **Safe AI Adoption** strategies that protect your data while using new tech.
- **"How do I stop cyber attacks?"** -> I build **Business Protection** systems to safeguard your revenue and reputation.
- **"I don't understand what my tech team is saying."** -> I act as a **Translator & Advisor** to bridge the gap between CEO vision and Code.
- **"I need to modernize without breaking everything."** -> I specialize in **Risk-Managed Digital Evolution**.

### Core Pillars
1. **The Strategist**: Partnering with organizations to cut through the fog of complexity, providing strategic consulting and software architecture to turn uncertainty into a competitive edge.
2. **The Operator**: Rooted in institutional discipline. Leading at the intersection of national security and the digital frontier.
3. **The Builder**: Turning strategy into code. Architecting tools like Project ARES to automate intelligence and solve hard problems.

### Key Projects
- **Curated Intelligence**: A specialized intelligence platform eliminating information overload by aggregating thousands of feeds into high-fidelity signal. (https://ci.orlabs.dev)
- **Obsidian Rowe Platform**: A strategic consulting framework bridging complex cybersecurity compliance and actionable AI-driven intelligence. (https://www.obsidianrowe.com)

### Recent Transmissions (Sunday Musings)
${posts?.map(post => `
#### [${post.title}](${baseUrl}/musings/${post.slug})
${post.excerpt || 'No summary available.'}
`).join('')}

---
Generated by erichaupt.com/llms.txt
`.trim();

    return new Response(content, {
        headers: {
            'Content-Type': 'text/plain; charset=utf-8',
            'Cache-Control': 'public, max-age=3600, s-maxage=3600',
        },
    });
}
